// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.szanto.domain;

import org.springframework.beans.factory.annotation.Configurable;
import org.szanto.domain.Topping;

privileged aspect Topping_Roo_Configurable {
    
    declare @type: Topping: @Configurable;
    
}
