// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.szanto.domain;

import org.springframework.beans.factory.annotation.Configurable;
import org.szanto.domain.BaseIntegrationTest;

privileged aspect BaseIntegrationTest_Roo_Configurable {
    
    declare @type: BaseIntegrationTest: @Configurable;
    
}
